### ISSUE TITLE
Splitting Stacks

### ISSUE THREAD

**Issue by montygommo** [AdiAddons/AdiBags#134]
I seem unable to split stacks if I have them combined (IE I have 20 food, and want to trade 5 to someone)

**Comment by Talyrius** [comment]
I just confirmed that splitting stacks still works just fine. Make sure you've selected the correct options.
![image](https://cloud.githubusercontent.com/assets/1068810/19857669/c50ba620-9f3b-11e6-890b-d22363bc2f12.png)

**Comment by David-EU** [comment]
This suck and even I love the addon it just make me want to remove it, which is not the best because it still a great addon, appart that point. So I must desactivate the addon and reload EACH time I want to trade a part of a stack, well do you really think it's an usefull design ?

![image](https://user-images.githubusercontent.com/9978015/34339754-b3811f4c-e978-11e7-8444-8e8d732060fb.png)

I followed your instruction and selecting, for example, 5 of my 90 stacks and put them into the mail just put everything (the 90!), it doesn't work like you say.
Please change this behavior and let us select how much objects we want to trade in a simplier and **user friendly** way.

**Comment by Jakobud** [comment]
Honestly I'm not sure why this was closed a long time ago. Separate Incomplete Stacks is not adequate for splitting when you have merged stackable items.

Example:

I have 20x Super Mana Potions. Super Mana Potions stack in groups of 5. My friend asks me for 5 potions. I am unable to split out a stack of 5 Super Mana Potions because 5 is not an incomplete stack. So after splitting out 5 potions Adibags still shows a single stack of 20 Mana Potions.

It would be really nice if when you manually split out anything, the "Merge Stackable Items" option is temporarily turned off so that you can see your item stacks that you just split.
