### ISSUE TITLE
Font sizes

### ISSUE THREAD

**Issue by 2ndHouse** [AdiAddons/AdiBags#198]
I'm having a strange issue where I can only select certain font sizes, many sizes seem to be unavailable. If I select 14, the slider moves to 13. If I select 15 or 16 the slider moves to 17. Basically, the font sizes of 14, 15, 16 are not available.  I'm guessing there are more sizes that won't apply, those are the only ones I have tested. Adibags is the only addon I have that has this issue with fonts.

**Comment by rubyrabble** [comment]
I've noticed that the font sizes only allow increments of 4. Also, the scales vary from character to character. Example: Character 1 will have even numbered increments, but Character 2 will have odd numbered increments. Not sure why, but it's been that way since I started using Adibags in 7.0 (I wouldn't know from before that). Copying profiles from character to character will not change the odd/even problem either. It would definitely be a quality of life improvement to see font sizes in increments of 1 so you can chose every profile to have the same number and get some leeway between fonts that are too large or too small. I'm a 14 fan myself, but I can't use 14 at all. 

Also, the gold currency numbers do not seem to be affected by font style chosen. Some alts will have the font I chose, some will have the default font and it will never change no matter what I try (copying profiles, setting all addons to the same font, check marking the small option).
