### ISSUE TITLE
inside my bags

### ISSUE THREAD

**Issue by steph33240** [AdiAddons/AdiBags#235]
Hello, here is every opening of my bags my objects are never in the same places, is it possible to freeze the organization of the bag with adibags.

 thank you

**Comment by SpareSimian** [comment]
Every time you open your bags with identical content, it should open with the same layout. But if you change the number of items in each section, the layout is going to change, to prevent overlap. The addon can't predict how many of each section (if any) is present so it can't produce a consistent layout.

What might be possible is to add a minimum size for all sections so that the overall bag is usually the same. Would you have a big enough screen for that? I know I wouldn't. 

One thing that would help me is to not squash two 2-item sections into one 4-item column. I find it harder to find things that way.
