### ISSUE TITLE
suggestion: ilevel module - show numbers at bottom of the item

### ISSUE THREAD

**Issue by mitterman2** [AdiAddons/AdiBags#303]
i couldnt see an option to display the ilevel on gear in bags at the bottom of the icon instead of the top. 
this was interfering with the pawn upgrade arrow which is also not moveable. 
changing line 104 in itemlevel.lua to: text:SetPoint("BOTTOMLEFT", button, 3, 1) 
this changed it to display at bottom. 
perhaps this could be an option in the config? 

great addon btw and thanks for all the hard work!

**Comment by Beet4** [comment]
You got my vote on this, it's has been bugging me for quite some time that the upgrade icon is covered by the ilvl.

**Comment by ZehelFenris** [comment]
i had the problem that both my pawn upgrade arrow and my addon that shows if i got the transmog or not is both on the top of the item which makes the top quite cluttered if i have a BoE item i havent learned look from thats an upgrade in my inventory

**Comment by Alyred** [comment]
This has actually been fixed in Pull #206 and has been working well since (though the menu layout could use some alignment). I'm not sure why this hasn't been merged, honestly.
Check the code there, but it will take some manual editing since some of the files have had some updates to the numbers to adjust for the iLevel squish.

**Comment by Alyred** [comment]
Any idea when we can get this merged? Testing has gone well, but we're starting to see other pulls that might conflict.
#499 should be merged in too, I'll post a reminder there.
