### ISSUE TITLE
add filters for ItemRack item sets (for Classic)

### ISSUE THREAD

**Issue by Lupe4js** [AdiAddons/AdiBags#394]
Hello,

I see that Adibags have an extension for outfitter set : AdiBags_Outfitter.
However Outfitter does not exit on classic and people rely on ItemRack to make sets.

I would really appreciate if I could have ItemRack sets filters.

Thank you,
An hybrid Druid with too many item sets in his bag.

**Comment by apottere** [comment]
I have a very beta ItemRack filter, but it requires this change to be pulled first: https://github.com/Rottenbeer/ItemRack/pull/51

**Comment by apottere** [comment]
Once this is reviewed, it should be good to go: https://www.curseforge.com/wow/addons/adibags-itemrack

**Comment by Lupe4js** [comment]
That awesome :)
Following this one. Keep up the good  work <3

**Comment by apottere** [comment]
Well, it's not showing up on curseforge's search or in the twitch client, and I contacted support and they said it could take up to two weeks to display because it has an underscore in the name.... but here's the link if you want to download it manually: https://www.curseforge.com/wow/addons/adibags-itemrack

**Comment by Lupe4js** [comment]
Nice, trying this tonight
