### ISSUE TITLE
Soulshards need to be excluded from tracked new items

### ISSUE THREAD

**Issue by Elwarc** [AdiAddons/AdiBags#440]
Every time you create a soulshard or get one back when you jump on the windrider, because your pet despawns, it thinks all soulshards in your inventory are new and puts them into recent items.

it would be nice if they could be blacklisted from recent items, just like junk items

**Comment by SpareSimian** [comment]
I'm using a shard bag, so all my shards go into a section labeled "4". A more useful description would be nice, but I don't recall my shards going into the New section since I got the bag. (A similar issue happens with hunter ammo and with herbs into an herb bag. The section name ends up being the bag number. For ammo I've since created an ammo section.)

**Comment by Elwarc** [comment]
Well if you have the bag view enabled then that is the case yes.
If you see categories like "Junk", "Consumables", "Quest" ect, then whenever you pickup a new item, it first goes into a secton called "Recent" on top.
In this view all soul shards go into "Reagents", but as soon as you create a new soul shard, it puts all soul shards you have in your inventory in the recent sectrion, which kind of defeats its purpose.
I managed to work around that by now, adding the soul shards in the Settings -> Filters -> Junk to the junk section and having junk items excluded from "Recent" items
