### ISSUE TITLE
Shadowlands BETA broken

### ISSUE THREAD

**Issue by Toldorn** [AdiAddons/AdiBags#475]
The addon doesn't open in BETA at all.

I see arkinventory has been updated, but cannot find any word of a working or community version of Adibags. Is one coming?

thanks!

**Comment by nedempst** [comment]
Seconding this I miss my adibags on the beta.  Can you please get us something so we can help you test it out :)

**Comment by Tac2cul** [comment]
If u go to pull requests and look at the shadowlands branch title and open it and then click on the files changed tab, and then go into each of your files and edit them as show in the files in each section of the changed files adibags will then function.

Thanks BourgeoisM for putting the changes up and atleast get a working copy

**Comment by nedempst** [comment]
Thanks!

------ Original Message ------

**Comment by nedempst** [comment]
It works seems like there is a delay when it loads and it seems to reset 
all items back to new items when you restart but otherwise great. :)

------ Original Message ------
From: "Neil D" <nedempst@gmail.com>
To: "AdiAddons/AdiBags" 
<reply@reply.github.com>
Sent: 27/09/2020 7:25:26 AM
Subject: Re[2]: [AdiAddons/AdiBags] Shadowlands BETA broken (#475)

**Comment by Tac2cul** [comment]
hmm i dont seem to have these issues, mine opens quickly and saves my settings even on logout

**Comment by nedempst** [comment]
Thanks will have to go through maybe I missed one.aby thoughts on which ?

**Comment by Tac2cul** [comment]
i havent got a clue

**Comment by nedempst** [comment]
Hey there. Found the mistake I omitted one entry in the OO.Lua and now 
that I updated it; it's perfect.

Thank you!

------ Original Message ------
