### ISSUE TITLE
Noty opening in pre-patch

### ISSUE THREAD

**Issue by Tovrin** [AdiAddons/AdiBags#486]
As the title says, the add-on is not opening in pre-patch.  

I wish I could tell you what the error message is, but there's a LOT of things not working in pre-patch and the bug message capture is one of them.

**Comment by chilblane** [comment]
Apparently SetBackdrop() was removed in 9.0.1, and one of the errors I _can_ see if referring to it.

**Comment by tehbob** [comment]
I went though the beta branch changes and made the changes to my local copy.  Once its updated for real, for sure (or those changes are merged) , use that one.  https://bit.ly/3lLK4zL

**Comment by Tovrin** [comment]
Awesome work.  Thank you.

**Comment by missebet** [comment]
> 
> 
> I went through the beta branch changes and made the changes to my local copy. Once it's updated for real, for sure (or those changes are merged), use that one. https://bit.ly/3lLK4zL

Not sure if this is something that can be fixed by you. I'm also sending this to the LibSaharedMedia-3 developer
In using your fix I'm getting the following errors:

1st Error:

6x Error loading AdiBags\libs\LibStub\LibStub.lua

2nd Error:

1x AdiBags\modules\CurrencyFrame.lua:128: attempt to index global 'CurrencyListInfo' (a nil value)
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Bags.lua"]:131: in function `GetFrame'
[string "@AdiBags\core\Bags.lua"]:83: in function `Open'
[string "@AdiBags\core\Bags.lua"]:209: in function `?'
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:447: in function `?'
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@LibSharedMedia-3.0-8020003\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...edia-3.0\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>
