### ISSUE TITLE
FYI: Sorting does not work because SortBags() appears broken in 9.0.1, not AdiBags.

### ISSUE THREAD

**Issue by JWalters-DravenIT** [AdiAddons/AdiBags#492]
https://us.forums.blizzard.com/en/wow/t/sortbags-not-functioning/683251

**Comment by JWalters-DravenIT** [comment]
The Bank and Reagents Bank Sorting appears to be working just fine.

**Comment by legowxelab2z8** [comment]
Sorting has worked for me since 9.0.1 on US realms. Before AdiBags was updated I was using the default UI and sorting worked.  With the updated AdiBags sorting also works for me.  This might be related to the server issues that have been going on.  Sorting items in your inventory sends a lot of item move requests and the servers might not be processing them when under load.
