### ISSUE TITLE
Currency's not showing and outtputing errors

### ISSUE THREAD

**Issue by dnorthrupva** [AdiAddons/AdiBags#497]
I'm getting frequent lua errors reg. Currency frame.

27x AdiBags\modules\CurrencyFrame.lua:128: attempt to index global 'CurrencyListInfo' (a nil value)
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Bags.lua"]:131: in function `GetFrame'
[string "@AdiBags\core\Bags.lua"]:83: in function `Open'
[string "@AdiBags\core\Bags.lua"]:119: in function <AdiBags\core\Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>

It references Ace3, but it resolved to AdiBags. I don't see anyone else reporting this issue, so is there something I should do? When I go to Plugins -> Currency, it doesn't show any Currencys selectable like it used too.

**Comment by legowxelab2z8** [comment]
Are you using the latest version of AdiBags (1.9.21)?  You can get the newest version from curseforge at https://www.curseforge.com/wow/addons/adibags

The error you are receiving shouldn't be possible in the current version.
https://github.com/AdiAddons/AdiBags/blob/2b62aabb1ca6671d0729cbbbec2e8fbaa5f09c20/modules/CurrencyFrame.lua#L124-L128

First currencyListInfo is defined as a local, the error report says it is a global.  
Those next three lines are error checking making sure there is a value and that it isnt "a nil value" specifically so that you won't get the exact error you are currently getting. 
your error message shows CurrencyListInfo, but the name in the current version is currencyListInfo   (case sensitive)
