### ISSUE TITLE
Legendary Base Items Not Stacking.

### ISSUE THREAD

**Issue by soundw4ve964** [AdiAddons/AdiBags#605]
The Shadowlands legendary base items don't stack completely when "Merge Unstackable Items" is enabled. I'm always ending up with multiple stacks of a single legendary item at a given level even though the item ID remains the same. (Multiple stacks of 225 leather helms for example)  
Current Version running: v1.9.25
![Screenshot (145)](https://user-images.githubusercontent.com/90939742/133863338-963329e9-4e48-4e1e-aaad-41962ac0fcb9.png)

**Comment by Cidan** [comment]
This is fixed in the CL mentioned above. This broken due to updates from Blizzard on how item links are parsed -- this was happening because each stack was crafted by a different player, and AdiBags wasn't ignoring the crafted by player tag for each item, adding another dimension to the stacks. This fix should go out in the next week or so. Thanks!
