### ISSUE TITLE
LUA error

### ISSUE THREAD

**Issue by matton300** [AdiAddons/AdiBags#610]
hi, im gettting this error when i sell something , and the position of the items doesn't refresh.

92x AdiBags\widgets\ContainerFrame.lua:998: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection5:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:998: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1069: in function <AdiBags\widgets\ContainerFrame.lua:1043>
[string "@AAP-Core\lib\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:129: in function <...eDragons\CallbackHandler-1.0\CallbackHandler-1.0.lua:129>
[string "=[C]"]: ?
[string "@AAP-Core\lib\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...eDragons\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AAP-Core\lib\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:445: in function `?'
[string "@AAP-Core\lib\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...eDragons\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AAP-Core\lib\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...eDragons\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AAP-Core\lib\HereBeDragons\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...eDragons\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?

**Comment by Weetbix813** [comment]
I get a similar error:

4x AdiBags\widgets\ContainerFrame.lua:998: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection14:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:998: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1069: in function <AdiBags\widgets\ContainerFrame.lua:1043>
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:129: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:129>
[string "=[C]"]: ?
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:431: in function `?'
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
[string "=(tail call)"]: ?
