### ISSUE TITLE
Bug in sorting

### ISSUE THREAD

**Issue by DrLip** [AdiAddons/AdiBags#618]
![image](https://user-images.githubusercontent.com/95160672/143732507-9f33769d-20af-434e-bc33-55272d239eff.png)
  
  they have to be in the skinning tab
  but in the new update its look like this 
  before update :
![image](https://user-images.githubusercontent.com/95160672/143732569-7cefeaaa-d9c6-42a0-8668-77d6b9fdae99.png)

**Comment by Talyrius** [comment]
First, I'd suggest that you reduce the amount of currencies you're tracking as that's what's causing your bag to become so wide. As for the skins appearing in the _Recent Items_ section instead of the _Skinning_ one, that's completely expected behavior for items that were recently added to the bag. If you want to force these items to be sorted to their respective sections, simply click the _Recent Items_ section header (the text itself is a button).
