### ISSUE TITLE
AdiBags Error on Item Upgrade

### ISSUE THREAD

**Issue by kj23decker** [AdiAddons/AdiBags#620]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'AdiBags' tried to call the protected function 'UpgradeItem()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `UpgradeItem'
[string "@Blizzard_ItemUpgradeUI\Blizzard_ItemUpgradeUI.lua"]:104: in function `OnConfirm'
[string "@FrameXML\StaticPopup.lua"]:325: in function `OnAccept'
[string "@FrameXML\StaticPopup.lua"]:5137: in function `StaticPopup_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Happens often when using any of the item upgrade NPC's such as Aggressor Zo'dash. Does not trigger 100% of the time, but well over 50%. The game requires me to disable AdiBags in order to upgrade items from that point until I restart the game. Then it could work a few times, or immediately re-occur.

**Comment by Talyrius** [comment]
AdiBags is unlikely at fault here. It uses several libraries that are shared among many other addons and because they're loaded alphabetically, it often gets falsely blamed for the taint introduced by these misbehaved addons.

BTW, you do not need to disable AdiBags when the game suggests that you do so—simply reload your UI (`/reload`). Getting in combat is likely what'll cause this taint to recur.
