### ISSUE TITLE
Any change on making AdiBags available on Wago?

### ISSUE THREAD

**Issue by Vakke** [AdiAddons/AdiBags#630]
Any change on making AdiBags also available on Wago?

Cursefore's new API is trying to kill 3rd party addons managers and as I use Windows Insider I cannot download or use Curseforge. This also applies to Linux users.

Wago for example is supporting both platforms it would help us keep on using the addon!

**Comment by Daegalus** [comment]
Or if not Wago, WoWUp and WoWInterface are good choices too. I would love to not use Curse anymore.

**Comment by SpareSimian** [comment]
I use Ajour to update my addons and today, May 1, it's unable to connect to Curseforge. It looks like Overwolf has finally made good on locking out 3rd party updaters that run ad-free and update all my addons in the blink of an eye. 

https://github.com/ajour/ajour/issues/746

In principle, Ajour can download addons directly from GitHub if a suitable zip file is included there under releases.

**Comment by Frici42** [comment]
Another voice to add on the "consider supporting other providers" pile ( and a dup issue at #633 )
With curse V1 now closed and V2 unlikely to be giving keys out to most smaller managers, we are left with no option other than updating by hand or being forced to abandon our favorite addon managers to use the only client that supports curse (instead of a client supporting multiple providers).

No matter which alternative provider it is, I would just love to see adibags available in a non curse environment for sure.

**Comment by Daegalus** [comment]
Actually, all we really need is all those tags to be made into GitHub release. And then at minimum, people can use the WoWUp GitHub integration to auto update.

Using the Bigwigs releaser or a variation of it could help. I know ArkInventory forked it to use it for their own TOC setup that didn't play nice with BigWigs releaser. So you can even look there for inspiration. 

Also GitHub actions are publicly viewable so you can mix and match as you please from many of the other add-ons that already upload to multiple locations.

**Comment by Frici42** [comment]
Indeed even something as simple as tagging it here with the proper structure would be golden.
Both for things like WoWUp but also anything else tracking github.
As mentioned at least twice  as well the packager from bigwigs helps to automate that further with github actions even further if not completely now.

**Comment by Cidan** [comment]
Closing this in favor of #633!
