### ISSUE TITLE
ContainerFrame error

### ISSUE THREAD

**Issue by zezreli** [AdiAddons/AdiBags#635]
AdiBags\widgets\ContainerFrame.lua:998: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection3:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@AdiBags\widgets\ContainerFrame.lua"]:998: in function `LayoutSections'
[string "@AdiBags\widgets\ContainerFrame.lua"]:1069: in function <AdiBags\widgets\ContainerFrame.lua:1043>
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:129: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:129>
[string "=[C]"]: ?
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Core.lua"]:431: in function `?'
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59>
...
[string "@FrameXML\UIParent.lua"]:3001: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:3081: in function `HideUIPanel'
[string "@FrameXML\UIParent.lua"]:2734: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3602: in function `HideUIPanel'
[string "@FrameXML\UIParent.lua"]:3762: in function `CloseWindows'
[string "@FrameXML\UIParent.lua"]:3808: in function <FrameXML\UIParent.lua:3798>
[string "=[C]"]: in function `securecall'
[string "@FrameXML\UIParent.lua"]:4451: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

**Comment by Kekass** [comment]
I'm  getting similar errors in tbc classic version

`Message: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:898: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection2:SetPoint.
Time: Sat Jun 11 20:31:41 2022
Count: 1
Stack: Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:898: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: AdiBagsSection2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:898: in function `LayoutSections'
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:969: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:943>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:370: in function `RefreshContents'
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:355: in function `ResumeUpdates'
[string "@Interface\AddOns\AdiBags\widgets\ContainerFrame.lua"]:338: in function <Interface\AddOns\AdiBags\widgets\ContainerFrame.lua:332>
[string "=[C]"]: in function `Show'
[string "@Interface\AddOns\AdiBags\core\Bags.lua"]:89: in function `Open'
[string "@Interface\AddOns\AdiBags\core\Hooks.lua"]:112: in function <Interface\AddOns\AdiBags\core\Hooks.lua:109>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "OPENALLBAGS"]:1: in function <[string "OPENALLBAGS"]:1>

Locals: (*temporary) = AdiBagsSection2 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 2
 count = 2
 total = 2
 name = "Free space"
 category = "Free space"
 height = 1
 key = "Free space#Free space"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPLEFT"
(*temporary) = AdiBagsSection4 {
 0 = <userdata>
 acquired = true
 buttons = <table> {
 }
 Header = <unnamed> {
 }
 slots = <table> {
 }
 width = 1
 count = 1
 total = 1
 name = "Mount"
 category = "Miscellaneous"
 height = 1
 key = "Miscellaneous#Mount"
 freeSlots = <table> {
 }
 container = AdiBagsContainer1 {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = 10.500000
(*temporary) = 0
`

**Comment by Cidan** [comment]
Please create a new bug if it's still happening, and use the new bug reporting template please. Thanks!
