### ISSUE TITLE
Void Storage

### ISSUE THREAD

**Issue by ghost** [AdiAddons/AdiBags#64]
This is a question and not a bug report (sorry, could not find any other place to ask). Could AdiBags work with Void Storage? I would love to be able to create "sets" or at least better organize things.

Thanks,

Roc

**Comment by VulcanTourist** [comment]
While AdiBags can't work with guild bank storage because of the shared nature of it, that isn't the case with void storage.  Is there something utterly different about the way that storage is handled?  Would the "tabs" be a stumbling block?

**Comment by zarevucky** [comment]
>  Is there something utterly different about the way that storage is handled?
There is, and I think it's quite obvious when you see how Void Storage works.

But other than that, it's quite possible that some future version of AdiBags might include a replacement for Void Storage window. However, it would be quite a lot of work and I doubt anyone has enough interest to work on that right now.

**Comment by VulcanTourist** [comment]
In retrospect after your reply I'm having a "duh" and "d'oh!" moment, since I wasn't even thinking about the GOLD FEES portion of the process.  Yep, it's still storage, but otherwise it's utterly different the way it's handled.  While it might be a nice integration to have one's categories extended there, it's not the crucial usage.  That is already admirably accomplished aside from the one bug I encounter routinely.
