### ISSUE TITLE
Question: Wotlk equipment manager section

### ISSUE THREAD

**Issue by JHills3** [AdiAddons/AdiBags#640]
Hi, Mate big fan of the addon.

Will this feature be supported in WOLTK classic?
![image](https://user-images.githubusercontent.com/90083925/183816439-33505b77-931a-404a-a105-d4201919026f.png)

**Comment by Talyrius** [comment]
If Blizzard implements it, yes. Otherwise, you'll need to use additional addons such as [ItemRack](https://www.curseforge.com/wow/addons/itemrack) & [AdiBags - ItemRackSets](https://www.curseforge.com/wow/addons/adibags-itemracksets) or [Outfitter](https://www.curseforge.com/wow/addons/outfitter-classic) & [AdiBags_Outfitter](https://www.curseforge.com/wow/addons/adibags_outfitter).

**Comment by JHills3** [comment]
Wonderful news. It looks like blizzard is implementing it: 
![image](https://user-images.githubusercontent.com/90083925/185347119-c82d272b-b7e6-4a64-be03-1665e1728330.png)

Appreciate your work mate.
