### ISSUE TITLE
Currency display on Wrath

### ISSUE THREAD

**Issue by jelmerj** [AdiAddons/AdiBags#707]
Wrath Classic re-introduced the Currency tab, containing stuff like the pvp marks and badges/emblems. Would it be possible to reinstate the currency display on the bag for wrath?

Simply modifying CurrencyFrame.lua to make it load for Wrath doesnt do the trick unfortunately. It results in this error:

`1x AdiBags\modules\CurrencyFrame.lua:131: attempt to call upvalue 'GetCurrencyListSize' (a nil value)
[string "=[C]"]: ?
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...rap\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Scrap\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@AdiBags\core\Bags.lua"]:131: in function `GetFrame'
[string "@AdiBags\core\Bags.lua"]:83: in function `Open'
[string "@AdiBags\core\Bags.lua"]:119: in function <AdiBags\core\Bags.lua:115>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "TOGGLEBACKPACK"]:1: in function <[string "TOGGLEBACKPACK"]:1>`

**Comment by rtroberts** [comment]
+1 from me, this feature would be quite nice to have.

**Comment by Talyrius** [comment]
> I was the person who posts #929 but this was a new issue for me. Because I had a working currency display on AdiBags for like a month and a half, until 3.4.1 dropped. Then it disappeared

I don't know what to tell you, but you're mistaken. Other than superficial changes with the new theme engine implementation (#880), the [CurrencyFrame module](https://github.com/AdiAddons/AdiBags/commits/master/modules/CurrencyFrame.lua) hasn't seen any updates since issue #707 was opened. Currently, AdiBags only supports currencies on retail, not classic/WotLK.
