### ISSUE TITLE
when logging into game

### ISSUE THREAD

**Issue by FireyDragon44** [AdiAddons/AdiBags#760]
### Addon Version

1.9.46 latest

### World of Warcraft Version

Retail

### Describe the bug

Message: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
Time: Sun Oct 30 15:29:58 2022
Count: 1
Stack: ...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/AdiBags/libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/AnnounceRare/Libraries/Ace3/AceConfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua"]:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceGUI-3.0"."

### Steps to reproduce

have  no idea. I get it when logging into the game.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
Do you get this error message when only AdiBags is enabled? If so, how are you installing the addon?

**Comment by FireyDragon44** [comment]
Apparently it doesn't work with a lot of my addons. Once I uninstalled 2 addons I haven't had the error yet which I don't get why it wont work with them... I download using curseforge app.

**Comment by Cidan** [comment]
The checkbox you are asked to check when filing a bug, asks you to make sure you only have AdiBags enabled and nothing else. Please make sure when filing bug reports in the future, that you follow instructions so that we can quickly assess the validity of bugs.

This does not look like an AdiBags error, and it's likely your other addons have an out of date set of dependencies. Please contact those authors and have them update their libraries.

Thanks!
