### ISSUE TITLE
[Feature]: Option to choose place currency value before currency.

### ISSUE THREAD

**Issue by YoloSwagin** [AdiAddons/AdiBags#775]
### Describe the feature

In the past, the currency value was always in front of the currency icon just like how gold is displayed. Recently, it was inversed that it now shows the currency icon and then the value which is odd. Is it possible to add an option to have it back to how it used to be?

### Describe the implementation

An option in the currency menu under "Layout" to have the value in front of the currency icon, like how  gold is displayed.

**Comment by Cidan** [comment]
The reason for this is the new multi-row display for currencies aligns on icons. I actually did try aligning on text as you suggested, but it was extremely messy. I also toyed with aligning right instead of left, but that didn't work well either due to the bag expanding right, not left, when adding new sections.

We will likely not implement this, and in fact, change gold to fit like currencies.
