### ISSUE TITLE
Bags closing everytime after taking/putting an item from/to bank / whenever I sell something to a vendor

### ISSUE THREAD

**Issue by DrExpress1** [AdiAddons/AdiBags#816]
### Addon Version

v1.9.48

### World of Warcraft Version

Retail

### Describe the bug

Whenever I want to take or put something from/to the bank it transfers the item and it closes all bags instead of staying opened. The same happens if I want to sell stuff from my bag with clicking on the item(item sells)

### Steps to reproduce

1. Open the bank
2. Take something out/put something in it
3. Get the item transfered as it should be but the bag closes
(additional) 4. Try to sell an item with right clicking while a vendor window is open.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by fai1337** [comment]
I am glad to see I'm not the only person having this problem! Oddly enough, it's only happening on half of my toons. Furthermore, when I tried to save a non-problematic toon's adibags profile, and then use that profile on a problematic toon, the problem was still there. Tbh all my toons use the same default profile anyway, but I figgered it couldn't hurt to try.

**Comment by Talyrius** [comment]
See #800.

**Comment by fai1337** [comment]
THANK YOU! I appreciate your taking the time to point me in the right
direction!
