### ISSUE TITLE
Subcategories broken in 1.9

### ISSUE THREAD

**Issue by Zarggg** [AdiAddons/AdiBags#85]
Since updating to 1.9, items used in crafting/trade skills are no longer divided into subcategories, but are instead grouped together in a single "tradeskills" group. Is this a bug, or is this intentional and I will have to make subgroups for ores, herbs, etc. manually?

**Comment by Cidan** [comment]
I've temporarily fixed this for enUS. This broke because Blizzard changed what the top level category is named; Trade Goods -> Tradeskills. Unfortunately the i18n library does not have this updated string yet.

I'll send the enUS fix up with my PR and ask the LibBabble people to add the string so all locales work.

Thanks.
