### ISSUE TITLE
[WOTLK PTR BUG] All items show up as Rare quality color

### ISSUE THREAD

**Issue by Jakobud** [AdiAddons/AdiBags#851]
### Addon Version

v1.9.50

### World of Warcraft Version

Wrath PTR

### Describe the bug

![image](https://user-images.githubusercontent.com/87356/206742797-55bbab3d-f9cd-431b-8f9e-bffeb7d4b86c.png)

### Steps to reproduce

1. Open the bag

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
This one is interesting, because I've completely and totally disabled all borders, and all the borders still show up blue. Further, if I set all the borders manually to RGB 1,1,1 (white), I see both a white, and a blue border.

I'm not going to dig around Blizzard's UI code on this one for now. If this continues into release, I'll look there.
