### ISSUE TITLE
Today's update made my bag 100% scaled again, and displayed currencies all became unchecked.

### ISSUE THREAD

**Issue by Bronski** [AdiAddons/AdiBags#895]
### Addon Version

1.10.1

### World of Warcraft Version

Retail

### Describe the bug

After today's update, my bag reset to 100% scaled--and currencies no longer display at bottom. I'm not sure what else may be changed but it doesn't seem the entire settings were reset because the right-click-for-options is still disabled (as I had set previously).

### Steps to reproduce

1.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
The default option for bags is now 100% scaling instead of 80%. This aligns with how the WoW UI works in general, and prevents a default skew to scaling when users scale their entire UI down by X. You should be able to go into the settings and adjust it.

As for currencies, the defaults here were changed as well for new players. The default was to show every single currency for new users, which generally not a good style/form. You should be able to go back and select which currencies you want.
