### ISSUE TITLE
Missing AceEvent-3.0

### ISSUE THREAD

**Issue by SpareSimian** [AdiAddons/AdiBags#904]
### Addon Version

v1.10.3

### World of Warcraft Version

Retail

### Describe the bug

ItemDatabase.lua fails to load due to missing library. (I also checked the zip file.)

Message: Interface/AddOns/AdiBags/core/ItemDatabase.lua:30: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of "AceEvent-3.0".

### Steps to reproduce

Fails when addon loaded.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by Cidan** [comment]
I pulled the update from Curse -- WoW authentication servers are down and I can't test a fix. I'll have a fix out once WoW is back up.

**Comment by Cidan** [comment]
Post mortem here @Talyrius -- we had AceEvent installed via other addons, but it's not a part of AdiBags. Disabling all addons during testing except AdiBags would have caught this.

I'm going to remove the module call entirely and make ItemDatabase a simple table for now. Fix has been pushed to master, however I'm waiting for WoW to come back up before I push 1.10.4.

**Comment by SpareSimian** [comment]
I copied in AceEvent from the DataStore addon and updated the toc and will test once I can auth in.

The visual symptom is that a lot of my customized section assignments are dumping into the Miscellaneous section. Which is probably because ItemDatabase is too fundamental to the addon and its absence causes all kinds of secondary effects.

**Comment by Cidan** [comment]
@SpareSimian ItemDatabase is the start of a new framework that will more logically break up the monolithic `addon` table into several sub-tables. It was part of a change in which we introduce automated categories based on expansion pack for trade goods. However, since this was called during the main category construction, and it failed, the whole bag construction would fail too.

**Comment by Cidan** [comment]
Fixed, but I found another issue when testing that is... really puzzling me. Give me a few.

**Comment by Cidan** [comment]
v1.10.4 pushed!

**Comment by SpareSimian** [comment]
I'm quite excited about the new feature, been following that in the other issue. But "no battle plan survives contact with the enemy". 😉

**Comment by Cidan** [comment]
Heh, you said it. A part of what we're working on is rewriting how parts of the addon work in general, so that errors like these can be caught by the linter. Because Lua is dynamically typed, there's no real way to catch missing references without type annotations, which AdiBags does not have (yet).

Sorry about that!
