### ISSUE TITLE
[Feature]: Improved Banking

### ISSUE THREAD

**Issue by phuze** [AdiAddons/AdiBags#915]
### Describe the feature

Banking feels clumsy with having to hit that little button to swap between the reagent view, or the main bank view. It would be great if AdiBags had options for any (ideally all), of:

- Choosing a default view when opening bank (ie: either the reagent or main tabs).
- Having a singular, combined bank view, such that switching is no longer necessary.
- Displaying both the main and reagent bank windows at the same time.

I think any of these options would help improve banking, notably two and/or three.

### Describe the implementation

When I go to the config options, I would like to see additional options under the "Bags" submenu, that would allow you configure one, or all, of the functions noted previously.

**Comment by Cidan** [comment]
Thank you for the feedback!

Unfortunately, this isn't really possible because of the way that Blizzard has written the API for the bank in general. When you open the bank without AdiBags enabled, you'll notice there is a tab you have to click in order to switch to the reagent bank. This isn't just for show, but actually sets a few different internal states in the Blizzard WoW client, such as which action to take when right clicking on an item, which item data to load for display, and so on.

Now, we can programmatically decide which "bag" to show under the hood, but there's no clean way to decide where an item should go on right click in 10.x, because Blizzard has attached taint to bag button interactions.

I think what would be more valuable here, and a better experience in general, is rethinking the way players switch between bank tabs. I'm not a super huge fan of the title bar buttons in general as far as user experience goes, and while it is something I want to eventually address, it won't be for a while to come.

Thank you again for your feedback :)

**Comment by SpareSimian** [comment]
How about presenting the bank as a tabbed notebook? Tabs are easier to hit than tiny buttons. 

It might also be desirable to display the main bags as a 3-tab notebook, with "All", "Reagents", and whatever one calls everything not a reagent. 

Do you have any control over the empty slot count in the bag list at the bottom right? I'd love to see that show only non-reagents since my reagent bag rarely runs out of slots, but my other bags constantly do.
