### ISSUE TITLE
Hidden bag items are shown off to the side and sometimes over other bag items

### ISSUE THREAD

**Issue by jkemouse11** [AdiAddons/AdiBags#969]
### Addon Version

1.10.16

### World of Warcraft Version

Retail

### Describe the bug

I have a set of items that I filter into a category called "hide," including my hearthstone, gateway control shard, pvp trinket, etc. In the visibility setting, I deselect that category so those items are not shown. 

When I open my bags, sometimes those items are not hidden and they are drawn on top of other items or they are drawn off the inventory screen. If I close and open my bags, they stay in that location. If I go to visibility and check "hide" category (to "show" them) and then uncheck "hide" category again, they will hide appropriately for a bit. 

The screenshot shows the gateway control shard and the pvp trinket drawn off to the side of the bag frame. In this instance, the rest of the items seem to be drawn appropriately, but sometimes they are drawn on top of other items in the bag frame as well. 

![adibags issue Screenshot 2023-05-28 001607](https://github.com/AdiAddons/AdiBags/assets/2990675/596a6197-7d13-40de-a95d-a623b4972b9d)

### Steps to reproduce

1. Create a filter of items you want to hide.
2. In visibility settings, uncheck that category so the items hide
3. Open bags 

Expected results: All items in that category are hidden
Actual results: Sometimes some of the items are drawn over top of some of the other bag slots, and sometimes off the bag frame as well.

### Verification

- [X] I have disabled all other addons and made sure this bug is triggered only with AdiBags enabled

**Comment by bloerwald** [comment]
I assumed this was an effect of #964's `< 0` condition, but it seems that's not the case (I tried debug logging there, but it doesn't show up even when the issue happens). They aren't always off to the side, they might also just overlap, I guess the off-to-the-side happens when the layouting decides to resize the window. The borked section always seems to be a hidden section.

![image](https://github.com/AdiAddons/AdiBags/assets/2866005/44590af1-045e-4c37-abba-02bc95efa72e)
